

name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: 更新wakatime README
    runs-on: ubuntu-latest
    steps:
      - uses: sunpm/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_EDITORS: True
          DEBUG_LOGGING: True
          SHOW_OS: True
          LOCALE: zh
          SHOW_SHORT_INFO: False # 隐藏用户的简短有趣的事实信息
          SHOW_DAYS_OF_WEEK: False # 隐藏在一周中不同日期所做的提交
          SHOW_PROJECTS: False # 隐藏正在处理的项目
          SHOW_COMMIT: False # 隐藏提交统计信息
          SHOW_PROFILE_VIEWS: False # 隐藏配置文件视图
          SHOW_TOTAL_CODE_TIME: False # 隐藏代码时间
          SHOW_LINES_OF_CODE: False # 隐藏截至日期编写的代码行
          SHOW_LOC_CHART: False # 隐藏不同年份不同季度编写的代码行
          SHOW_TIMEZONE: False # 隐藏您所在的时区
          SHOW_UPDATED_DATE: False # 段落末尾显示更新日期
          SHOW_LANGUAGE_PER_REPO: False # 隐藏不同语言和框架的存储库数量

