
   
name: Waka Readme

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 1 * * 1'

jobs:
  update-readme:
    name: 更新wakatime README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_EDITORS: true
          SHOW_OS: true
          LOCALE: zh_CN
          SHOW_SHORT_INFO: false # 隐藏用户的简短有趣的事实信息
          SHOW_DAYS_OF_WEEK: False # 隐藏在一周中不同日期所做的提交
          SHOW_PROJECTS: False # 隐藏正在处理的项目
          SHOW_COMMIT: False # 隐藏提交统计信息
          SHOW_PROFILE_VIEWS: False # 隐藏配置文件视图
          SHOW_TOTAL_CODE_TIME: False # 隐藏代码时间
          SHOW_LINES_OF_CODE: False # 隐藏截至日期编写的代码行