
   
name: Waka Readme

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 1 * * 1'

jobs:
  update-readme:
    name: 更新wakatime README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_EDITORS: true
          SHOW_OS: true
          LOCALE: bn
          SHOW_SHORT_INFO: false
          SHOW_DAYS_OF_WEEK: False # 隐藏在一周中不同日期所做的提交